server:
  port: 8082

spring:
  application:
    name: beat-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:kuspid_db_primary}?currentSchema=beat_svc
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dcjo4leif}
  api-key: ${CLOUDINARY_API_KEY:137657341713195}
  api-secret: ${CLOUDINARY_API_SECRET:ERPWAGbm-R_rCl6rCotYjByvsEA}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics



